---
user_ansible_sshkeys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINttIG1i8IVuNL9dbWIO3mI2ys5fHJd+JifXnTlRZrpC brandon@desktop-windows
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICr8qzFfewAmvy0gs2HUZUksdHrTxp+POMQpFXC2pggA brandon@desktop-windows-wsl
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKhU59iaJDfAJNAWel+aAi4VRuhJHjC6rPJHR6et2AXo brandon@macbook-pro

user_unprivileged_setup: yes
user_unprivileged_sshkeys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICCbXpp6ejJKx41rBjqI6wjL0/eXPvAVIN+TioXwfz6D brandon@desktop-windows
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILLfR2NuXqu34kJkuXP2Lu8fX1FXvUN6WqCfJ7i9MrYf brandon@desktop-windows-wsl
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINoKAr3YHpb7My6qv5lb31XIvbtzb+4z9BpDFTjUiBze brandon@macbook-pro
